version: "3"

services:
  api:
    container_name: ifconfig_api
    image: mark314/geoip2-gql
    volumes:
      - /var/www/maxmind:/maxmind

  web:
    container_name: ifconfig_web
    image: mark314/ifconfig
    ports:
      - "3080:3080"
