version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ifconfig_api
    network_mode: "host"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: ifconfig_web
    network_mode: "host"
