version: "3"

services:
  api:
    container_name: ifconfig_api
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - /var/www/maxmind:/maxmind

  web:
    container_name: ifconfig_web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3080:3080"
