name: build & release

on:
  push:
    tags:
      - "*"

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@master

      # Create release
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true

      # Build
      - uses: actions/setup-node@master

      - name: Install node package
        run: |
          npm install

      - name: Build
        run: |
          npm run build
          tar -C $PWD -cvzf ifconfig.tar.gz dist

      # upload
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ifconfig.tar.gz
          asset_name: ifconfig.tar.gz
          asset_content_type: application/gzip
